[package]
name = "couchdb"
version = "0.0.1"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>"]
license = "MIT"
description = "A simple CouchDB client"
repository = "https://github.com/couchdb-rs/couchdb"
documentation = "https://couchdb-rs.github.io/couchdb/doc/latest/couchdb/"
keywords = ["couch", "couchdb", "database", "nosql"]

[dependencies]
hyper = "0.6"
regex = "0.1"
serde = "0.6"
serde_json = "0.6"
tempdir = "0.3"
url = "0.2"

[lib]
name = "couchdb"
