[package]
name = "couchdb"
version = "0.2.0"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>"]
license = "MIT"
description = "A simple CouchDB client"
repository = "https://github.com/couchdb-rs/couchdb"
documentation = "https://couchdb-rs.github.io/couchdb/doc/latest/couchdb/"
keywords = ["couch", "couchdb", "database", "nosql"]

[dependencies]
hyper = "*"
regex = "*"
serde = "*"
serde_json = "*"
tempdir = "*"
url = "*"

[lib]
name = "couchdb"
