[package]
name = "couchdb"
version = "0.5.1+master"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>"]
license = "MIT/Apache-2.0"
description = "CouchDB client library"
repository = "https://github.com/couchdb-rs/couchdb"
documentation = "https://couchdb-rs.github.io/couchdb/doc/v0.5.0/couchdb/"
keywords = ["couch", "couchdb", "database", "nosql"]

[dependencies]
hyper = "0.7"
regex = "0.1"
semver = "0.2.2"
serde = "0.6"
serde_json = "0.6"
tempdir = "0.3"
url = "0.5"

[lib]
name = "couchdb"
